---
title: "Report-001: MTB Survey Global Report"
author: "`r Sys.getenv('USER')`"
date: "`r strftime(Sys.time(),format='%F %T %Z')`"
output: 
  html_document: 
    theme: cosmo
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Molecular Tumor Board Survey

## Total Responders

There were __`r dim(mydata)[1]`__ completed surveys

```{r insttype}
mytable <- data.frame(table(mydata$gen_insttypeasfactor))
# mytable <- cbind( sum(mytable), mytable)
colnames(mytable) <- c('Institution Type','Frequency')
knitr::kable(mytable,caption = '')
```

```{r insttypeother}
mytable <- data.frame(mydata$gen_insttype_other[mydata$gen_insttype==4])
colnames(mytable) <- c('Institution Type (Other)')
knitr::kable(mytable,caption = '')
```

<p style="page-break-before: always" />

```{r submitterrole}
mytable <- data.frame(table(mydata$submitter_roleasfactor))
colnames(mytable) <- c("Submitter's Role","Frequency")
knitr::kable(mytable,caption = '')
```

```{r submitterroleother}
mytable <- data.frame(mydata$submitter_role_oth[mydata$submitter_role==99 & mydata$submitter_role_oth != ''])
colnames(mytable) <- c("Submitter's Role (Other)")
knitr::kable(mytable,caption = '')
```

<p style="page-break-before: always" />

## NGS Utilization

```{r usengs}
mytable <- data.frame(table(mydata$b2asfactor))
colnames(mytable) <- c('Do you use NGS testing for molecular profiling of advanced solid tumors, recommended by NCCN?','Frequency')
knitr::kable(mytable,caption = 'NGS Use')
```

<p style="page-break-before: always" />

### Sites That Do Not Use NGS Testing for Molecular Profiling of Advanced Solid Tumors (`r sum(mydata$b2==0)`)

```{r x1}
mytable <- data.frame(table(mydata$x1asfactor))
colnames(mytable) <- c(mymetadata$field_label[mymetadata$field_name=='x1'],'Freq')
knitr::kable(mytable,caption = '')
```

```{r x2}
mytable <- data.frame(table(mydata$x2asfactor))
colnames(mytable) <- c(mymetadata$field_label[mymetadata$field_name=='x2'],'Freq')
knitr::kable(mytable,caption = '')
```

```{r x3}
mytable <- data.frame(table(mydata$x3asfactor))
colnames(mytable) <- c(mymetadata$field_label[mymetadata$field_name=='x3'],'Freq')
knitr::kable(mytable,caption = '')
```

```{r x4}
mytable <- data.frame(table(mydata$x4asfactor))
colnames(mytable) <- c(mymetadata$field_label[mymetadata$field_name=='x4'],'Freq')
knitr::kable(mytable,caption = '')
```

```{r y1}
mytable <- data.frame(table(mydata$y1asfactor[mydata$b2==0]))
colnames(mytable) <- c(mymetadata$field_label[mymetadata$field_name=='y1'],'Freq')
knitr::kable(mytable,caption = '')
```

```{r y2}
mytable <- data.frame(table(mydata$y2asfactor[mydata$b2==0]))
colnames(mytable) <- c(mymetadata$field_label[mymetadata$field_name=='y2'],'Freq')
knitr::kable(mytable,caption = '')
```

<p style="page-break-before: always" />
